// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzYcsaB99-oRb7ESSA3MPOFgicPSlRquE',
    appId: '1:620806499633:web:c799ad8a5a7c6f24a6d410',
    messagingSenderId: '620806499633',
    projectId: 'split-expenses-70f9a',
    authDomain: 'split-expenses-70f9a.firebaseapp.com',
    storageBucket: 'split-expenses-70f9a.firebasestorage.app',
    measurementId: 'G-ZC19W0JJW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFeOzMJpTkXXX5XVsOB0FbTixU8hDbuqo',
    appId: '1:620806499633:android:b489dc9ff17669e7a6d410',
    messagingSenderId: '620806499633',
    projectId: 'split-expenses-70f9a',
    storageBucket: 'split-expenses-70f9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwE_mjCCFnULltqX6P_SLvV6O34oaf67I',
    appId: '1:620806499633:ios:d7fb5b936c4599c1a6d410',
    messagingSenderId: '620806499633',
    projectId: 'split-expenses-70f9a',
    storageBucket: 'split-expenses-70f9a.firebasestorage.app',
    iosBundleId: 'com.example.splitExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwE_mjCCFnULltqX6P_SLvV6O34oaf67I',
    appId: '1:620806499633:ios:d7fb5b936c4599c1a6d410',
    messagingSenderId: '620806499633',
    projectId: 'split-expenses-70f9a',
    storageBucket: 'split-expenses-70f9a.firebasestorage.app',
    iosBundleId: 'com.example.splitExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzYcsaB99-oRb7ESSA3MPOFgicPSlRquE',
    appId: '1:620806499633:web:b33252d7f23782c9a6d410',
    messagingSenderId: '620806499633',
    projectId: 'split-expenses-70f9a',
    authDomain: 'split-expenses-70f9a.firebaseapp.com',
    storageBucket: 'split-expenses-70f9a.firebasestorage.app',
    measurementId: 'G-9Z6FQ7E10F',
  );
}
